version: 2

sources:
  - name: staging
    database: de-capstone-project-23
    schema: globalterrorism_raw
    tables:
      - name: data
        description: |
          ## Overview
          The table contains global terrorism data
        columns:
          - name: eventid
            tests:
              - not_null